config/routes.rb
Rails.application.routes.draw do
  resources :service_types
  resources :schedules
  resources :expenses
  resources :estimates
  resources :charges
  resources :shipping_addresses
    devise_for :admins
    root 'home#home'
    resources :invoices
    get 'invoices_show_all' => 'invoices#show_all', as: 'show_all'
    get 'create_monthly_invoices' => 'clients#create_monthly_invoices'
    get 'last_service_price' => 'clients#last_service_price'
    get 'last_service_prices_by_name_address' => 'clients#last_service_prices_by_name_address'
    resources :clients
    resources :services
    post 'invoices/payment_reminder'
    get 'invoice_letter/:id' => 'invoices#letter', as: 'invoice_letter'
    post 'create_services' => 'clients#create_services'
    get 'home' => 'home#home'
    get 'prospects' => 'clients#prospects'
    get 'dashboard' => 'expenses#index'
    get 'schedule', :to => redirect('schedule.erb.html')
    get 'googlea87d8b3af5e98ec8.html', :to => redirect('googlea87d8b3af5e98ec8.html')
    get 'favicon.ico', :to => redirect('https://pandera.ml/images/pandera_app/favicon-32x32.png')
    get 'apple-touch-icon.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon.png')
    get 'apple-touch-icon-76x76.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-76x76.png')
    get 'apple-touch-icon-120x120-precomposed.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-120x120-precomposed.png')
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
    belongs_to :client

    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |estimate|
          csv << estimate.attributes.values_at(*column_names)
        end
      end
    end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
    respond_to do |format|
      format.html
      format.csv { send_data Estimate.all.to_csv }
      #format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
    @estimate = Estimate.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EstimatePdf.new(@estimate, view_context)
        send_data pdf.render, filename:
        "estimate_#{@estimate.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)

    respond_to do |format|
      if @estimate.save
        EstimateMailer.estimate_created(@estimate).deliver_now if @estimate.client.email.present?
        EstimateSmsMailer.estimate_created(@estimate).deliver_now if @estimate.client.phone.present? && @estimate.client.sms_gateway.present?
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render :show, status: :created, location: @estimate }
      else
        @client_id = params[:service][:client_id]
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { render :show, status: :ok, location: @estimate }
      else
        format.html { render :edit }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to estimates_url, notice: 'Estimate was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:description, :price, :client_id, :notes)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= form_for(@estimate) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% @estimate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="field">
    <% if params.has_key?(:client_id) %>
      <%= f.hidden_field :client_id, :value => params[:client_id] %>
    <% else %>
      <%= f.hidden_field :client_id, :value => @estimate.client_id %>
    <% end %>
  </span>
  <div class="field">
    <%= f.label :description %><br>
    <%= select_tag('description', options_from_collection_for_select(ServiceType.all, 'description', 'description'), prompt: '', class: 'description custom-select', style: 'width: 30%') %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/estimates/edit.html.erb
<h1>Editing Estimate</h1>

<%= render 'form' %>



<span class="page_footer">
  <%= link_to 'Show', @estimate %> |
  <%= link_to 'Back', estimates_path %>
</span>

app/views/estimates/index.html.erb
<h3 style="font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('estimates') %></h3>

<div id="estimates" class="card">
  <div class="table-responsive card-body">
    <table id="estimates_table" class="card-body table table-striped table-bordered table-hover table-condensed table-responsive">
      <thead>
        <tr>
          <th style="width: 20%;"><%= t('description') %></th>
          <th style="width: 10%;"><%= t('price') %></th>
          <th style="width: 20%;"><%= t('client') %></th>
          <th style="width: 25%;"><%= t('notes') %></th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @estimates.each do |estimate| %>
          <tr>
            <td><%= estimate.description %></td>
            <td><%= estimate.price %></td>
            <td><%= link_to estimate.client.name, estimate.client %></td>
            <td><%= estimate.notes %></td>
            <td><%= link_to 'Details', estimate %></td>
            <td><%= link_to 'Agreement Form', estimate_path(estimate.id, :format => :pdf) %></td>
            <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
            <td><%= link_to 'Delete', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
	</div>
</div>

<br><br><br>

<span class="page_footer">
  <p style="text-align: right;margin-top:-23px;">
    <%= t('download') %>:
    <%= link_to "CSV", estimates_path(format: "csv") %>
  </p>
</span>


<br><br>

app/views/estimates/new.html.erb
<h1>New Estimate</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to 'Back', estimates_path %>
</span>

app/views/estimates/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @estimate.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @estimate.price %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @estimate.notes %>
</p>

<span class="page_footer">
  <%= link_to 'Edit', edit_estimate_path(@estimate) %> |
  <%= link_to 'Back', estimates_path %>
</span>