config/routes.rb
Rails.application.routes.draw do
  resources :service_types
  resources :schedules
  resources :expenses
  resources :estimates
  resources :charges
  resources :shipping_addresses
    devise_for :admins
    root 'home#home'
    resources :invoices
    get 'invoices_show_all' => 'invoices#show_all', as: 'show_all'
    get 'create_monthly_invoices' => 'clients#create_monthly_invoices'
    get 'last_service_price' => 'clients#last_service_price'
    get 'last_service_prices_by_name_address' => 'clients#last_service_prices_by_name_address'
    resources :clients
    resources :services
    post 'invoices/payment_reminder'
    get 'invoice_letter/:id' => 'invoices#letter', as: 'invoice_letter'
    post 'create_services' => 'clients#create_services'
    get 'home' => 'home#home'
    get 'prospects' => 'clients#prospects'
    get 'dashboard' => 'expenses#index'
    get 'schedule', :to => redirect('schedule.erb.html')
    get 'googlea87d8b3af5e98ec8.html', :to => redirect('googlea87d8b3af5e98ec8.html')
    get 'favicon.ico', :to => redirect('https://pandera.ml/images/pandera_app/favicon-32x32.png')
    get 'apple-touch-icon.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon.png')
    get 'apple-touch-icon-76x76.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-76x76.png')
    get 'apple-touch-icon-120x120-precomposed.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-120x120-precomposed.png')
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
      before_create :compute_invoice_num
      before_save :check_if_paid
      before_create :link_services_to_invoice
      before_create :compute_total
      before_destroy :unlink_services_to_invoice
      belongs_to :client
      validates :client_id, presence: true
      has_many :services, dependent: :destroy

      def compute_invoice_num
          self.invoice_number = (Invoice.all.length <= 0) ? ((1).to_s + Time.now.year.to_s ).to_i : ( (Invoice.last.id + 1).to_s + Time.now.year.to_s ).to_i
      end

      def check_if_paid
          if self.paid
            self.services.each do |service|
                service.paid = true
                service.save!
            end
          end
      end

      def link_services_to_invoice
        self.services = self.client.services.where("paid IS NOT TRUE").where("invoice_id IS NULL")
      end

      def unlink_services_to_invoice
        self.services.each do |service|
            service.invoice_id = nil
            service.save!
        end
      end

      def compute_total
          prices = self.client.services.where("paid IS NOT TRUE").where("invoice_id IS NULL").pluck(:price)
          if prices.length<=0
            self.total = 0
          else
            self.total = prices.inject(0){|sum,x| sum + x }
          end
      end

      def self.search(search)
        if search
			joins('JOIN clients ON clients.id = invoices.client_id').
            where(' clients.name ILIKE ? OR CAST( invoice_number AS text ) ILIKE ?
				OR CAST(maturity AS text) ILIKE ? OR description ILIKE ?
				OR CAST(total as text) ILIKE ?',
             "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        else
            where(nil)
        end
    end

    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << ['Client Name', 'Invoice Number', 'Description', 'Total', 'Paid', 'Check Number']
        all.each do |invoice|
            data = [invoice.client.name, invoice.invoice_number, invoice.description, invoice.total, invoice.paid.present?, invoice.check_number]
            csv << data
        end
      end
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    #@invoices = Invoice.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 15, :page => params[:page])
    @invoices = Invoice.includes(:client).search(params[:search]).order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
    if params[:overdue]
      @invoices = @invoices.where('? > maturity', Date.today).where('paid IS NOT TRUE')
    end

    respond_to do |format|
      format.html
      format.csv { send_data Invoice.includes(:client).to_csv }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice, view_context)
        send_data pdf.render, filename:
        "invoice_#{@invoice.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf",
				disposition: "inline"
      end
    end
  end

  def letter
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoiceLetterPdf.new(@invoice, view_context)
        send_data pdf.render, filename:
        "invoice_#{@invoice.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def show_all
    @invoices = Invoice.where("paid IS NOT TRUE")
		respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoices, view_context)
        send_data pdf.render, filename:
        "all_unpaid_invoices.pdf",
        type: "application/pdf",
				disposition: "inline"
      end
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  def payment_reminder
    @invoice = Invoice.find(params[:id])
    InvoiceMailer.invoice_reminder(@invoice).deliver_now if @invoice.client.email.present?
    InvoiceSmsMailer.invoice_reminder(@invoice).deliver_now if @invoice.client.phone.present? && @invoice.client.sms_gateway.present?
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    respond_to do |format|
      if @invoice.save
        InvoiceMailer.invoice_created(@invoice).deliver_now if @invoice.client.email.present?
        InvoiceSmsMailer.invoice_created(@invoice).deliver_now if @invoice.client.phone.present? && @invoice.client.sms_gateway.present?
        format.html { redirect_to invoices_path, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        @client_id = params[:invoice][:client_id]
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if params[:invoice][:paid] == '1'
        @invoice.services.each do |service|
          service.paid = true
          service.save!
        end
      end
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:client_id, :invoice_number, :maturity, :date_of_service, :description, :price, :total, :paid, :check_number, :payable_to)
    end

    def sort_column
      Invoice.column_names.include?(params[:sort]) ? params[:sort] : "invoice_number"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="field">
    <% if params.has_key?(:client_id) %>
      <%= f.hidden_field :client_id, :value => params[:client_id] %>
    <% else %>
      <%= f.hidden_field :client_id, :value => @invoice.client_id %>
    <% end %>
  </span>
  <div class="field">
    <%= f.label t('maturity') %><br>
    <%#= f.date_select :maturity, class: "form-control", style: "width: 25%" %>
    <%= f.date_select :maturity, {:order => [:month, :day, :year], :start_year => Time.now.year - 80, use_month_numbers: true}, {:class => "custom-select mini", style: "width: 10%"} %>

  </div>
  <div class="field">
    <%= f.label t('description') %><br>
    <%= f.text_area :description, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('paid') %><br>
    <%= f.check_box :paid, :class => "checkbox" %>
  </div>
  <div class="field">
    <%= f.label t('check_number') %><br>
    <%= f.text_field :check_number, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
      <%= f.label t('payable_to') %><br>
      <%= f.select :payable_to, options_for_select(ShippingAddress.all.map(&:name), @invoice.payable_to), {}, {class: 'sms_gateway custom-select', style: "width: 30%"} %>
  </div>
  <div class="actions">
    <%= f.submit t('save'), class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<style>
div#one {
    width: 75%;
    height: 130px;
    float: left;
}
div#two {
    margin-left: 15%;
    height: 110px;
}
.invoiceTitle{
  font-size: 30px;
}

</style>

    <section>
        <div id="one">
        <% sa = ShippingAddress.where("is_default IS TRUE").first %>
          <p><b> <%= sa.name %> </br>
          <%= sa.street %> </br>
          <%= sa.city + ', ' + sa.state + ' ' + sa.zipcode %></b> </p> </br>
        </div>

        <div id="two">
          <b> <span class="invoiceTitle">Invoice </span> </br>
          Date <%= invoice.created_at.strftime("%m/%d/%Y") %> </br>
          Invoice # <%= invoice.invoice_number %> </b>
        </div>
    </section>

    <section>
        <div id="one">
          <p><b> Bill To </b> </br>
           <%= invoice.client.name %> </br>
           <%= invoice.client.street_address %> </br>
           <%= invoice.client.city %> <%= invoice.client.zipcode %> </br>
           </p>
        </div>

        <div id="two">
          <p><b> Ship To </b> </br>
           <%= invoice.client.name %> </br>
           <%= invoice.client.street_address %> </br>
           <%= invoice.client.city %> <%= invoice.client.zipcode %> </br>
           </p>
        </div>
    </section>

    <section>
        <div id="one">
          <h3 style="margin-top: 75px;">Services</h3>
        </div>

        <div id="two">
        </div>
    </section>

    <div class="table-responsive ">
      <table id="invoice_print_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
        <thead>
          <tr>
            <th>Description</th>
            <th>Date of service</th>
            <th>Price</th>
            <th>Total</th>
          </tr>
        </thead>

        <tbody>
          <% invoice.services.each do |service| %>
            <tr>
              <td><%= service.description %></td>
              <td><%= service.date %></td>
              <td><%= service.price %></td>
              <td><%= service.price %></td>
                  <% prices = service.client.services.pluck(:price) %>
              <% '$' if prices.length>=1 %><% @total = prices.inject(0){|sum,x| sum + x } %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <section>
        <div id="one">
          <p><b> <%= sa.name %> </b></br>
          <%= sa.email %></br>
          <%= sa.phone %></br>
          <% sa_name = invoice.payable_to ? invoice.payable_to : sa.name %>
          -------------------------------- </br>
          Please make checks payable to: </br>
          <%= sa_name %> </br>
          </p>
        </div>

        <div id="two">
          <table id="invoice_print_table">
            <tr>
              <th>Subtotal:</th>

              <td>$<%= invoice.total %></td>
            </tr>
            <tr>
              <th>Sales Tax (0.0%)</th>
              <td></td>
            </tr>
            <tr>
              <th>Total</th>
              <td>$<%= invoice.total %></td>
            </tr>
            <tr>
              <th>Payments/Credits</th>
              <td></td>
            </tr>
            <tr>
              <th>Balance Due</th>
              <td>$<%= invoice.total %></td>
            </tr>
          </table>
        </div>
    </section>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to t('details'), @invoice %> |
  <%= link_to t('back'), invoices_path %>
</span>

app/views/invoices/index.html.erb
<h3 style="font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('invoices') %></h3>

<%= form_tag invoices_path, :method => 'get', :id => "invoices_search", :style => "margin: -37px 0 0 0;" do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= label_tag t('overdue') %>
    <%= check_box_tag :overdue,'yes', params[:overdue] %>
    <b><%= t('search') %>:  </b><%= text_field_tag :search, params[:search], style: "display: initial" %>
  </p>
<% end %>

<div id="invoices" class="card">
    <div class="table-responsive card-body">
      <table id="invoices_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
        <thead>
          <tr>
            <th style="width: 15%;"><%= t('client') %></th>
            <th style="width: 15%;"><%= t('invoice') %> ID</th>
            <th style="width: 15%;"><%= t('maturity') %></th>
            <th style="width: 15%;"><%= t('description') %></th>
            <th style="width: 15%;"><%= t('total') %></th>
            <th style="width: 10%;"><%= t('paid') %></th>
            <th style="width: 15%;"><%= t('check_number') %></th>
            <th colspan="6" style="text-align: center;"><%= t('actions') %></th>
          </tr>
        </thead>

        <tbody>
          <% @invoices.each do |invoice| %>
            <tr>
              <td>
              <% if !invoice.client.name.present? || invoice.client.name.empty? %>
                  <%= link_to invoice.client.id, invoice.client %>
                <% else %>
                  <%= link_to invoice.client.name, invoice.client %>
              <% end %> </td>
              <td><%= invoice.id %></td>
              <td><%= invoice.maturity %></td>
              <td><%= invoice.description %></td>
              <td><%= invoice.total %></td>
              <td><%= invoice.paid ? t('yes') : t('no') %></td>
              <td><%= invoice.check_number %></td>
              <td><%= button_to t('send_reminder'), invoices_payment_reminder_path(id: invoice.id), style: 'white-space: normal;', class: 'rick_button', method: :post, data: { confirm: 'Send an email?' } %> </td>
              <td style="padding-top: 15px;"><%= link_to t('pay'), new_charge_path(invoice_id: invoice.id), target: :_blank , class: 'rick_button' %> </td>
              <td><%= link_to t('details'), invoice_path(invoice.id, :format => :pdf) %></td>
              <td><%= link_to t('letter'), invoice_letter_path(invoice.id, :format => :pdf) %></td>
              <td><%= link_to t('edit'), edit_invoice_path(invoice) %></td>
              <td><%= link_to t('delete'), invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

<span  class="page_footer">
  <%= link_to t('create_all_monthly_invoices'), create_monthly_invoices_path %> |
  <%= link_to t('print_all_invoices'), show_all_path(:format => :pdf) %> |
</span>
<span  class="page_footer">
  <%= t('download') %>:
  <%= link_to "CSV", invoices_path(format: "csv") %>
</span>
<br/><br/>

<span class="page_footer">
  <% company_receivables = Invoice.where("paid IS NOT TRUE").pluck(:total) %>
  <b><%= t('receivables') %>:
  <% if company_receivables.length<=0 %>
    <%= '$0' %>
  <% else %>
   <%= '$' %><%= company_receivables.inject(0){|sum,x| sum + x } %></b>
  <% end %>
  <br>
  <b><%= t('services_without_invoice') %>: <%= Service.where("paid IS NOT TRUE").where(invoice_id: nil).count %>
  <br>
  <%= will_paginate @invoices, :previous_label => t('previous'), :next_label => t('next'), inner_window: 1, outer_window: 0 %>
  <br/>
</span>

<br/>
<br/>

<script>
    $( "#invoices_search" ).keyup(function() {
        search = $('#search').val();
        $.get( "/invoices?search="+search, function( data ) {
            data_html_obj = $($.parseHTML( data ) );
            div = data_html_obj.find('#invoices');
            $('#invoices').html(div);
        });
    });
</script>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to 'Back', invoices_path %>
</span>

app/views/invoices/payment_reminder.html.erb
<span class="page_footer">
  Reminder has been sent!
  </br>
  </br>
  <%= link_to 'Back', invoices_path %>
</span>

app/views/invoices/show.html.erb
<%= render 'invoice', invoice: @invoice %>

app/views/invoices/show_all.html.erb
<% @invoices.each do |invoice| %>
    <%= render 'invoice', invoice: invoice %>
    <% 23.times do |n| %>
        <br/>
    <% end %>
<% end %>