config/routes.rb
Rails.application.routes.draw do
  resources :service_types
  resources :schedules
  resources :expenses
  resources :estimates
  resources :charges
  resources :shipping_addresses
    devise_for :admins
    root 'home#home'
    resources :invoices
    get 'invoices_show_all' => 'invoices#show_all', as: 'show_all'
    get 'create_monthly_invoices' => 'clients#create_monthly_invoices'
    get 'last_service_price' => 'clients#last_service_price'
    get 'last_service_prices_by_name_address' => 'clients#last_service_prices_by_name_address'
    resources :clients
    resources :services
    post 'invoices/payment_reminder'
    get 'invoice_letter/:id' => 'invoices#letter', as: 'invoice_letter'
    post 'create_services' => 'clients#create_services'
    get 'home' => 'home#home'
    get 'prospects' => 'clients#prospects'
    get 'dashboard' => 'expenses#index'
    get 'schedule', :to => redirect('schedule.erb.html')
    get 'googlea87d8b3af5e98ec8.html', :to => redirect('googlea87d8b3af5e98ec8.html')
    get 'favicon.ico', :to => redirect('https://pandera.ml/images/pandera_app/favicon-32x32.png')
    get 'apple-touch-icon.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon.png')
    get 'apple-touch-icon-76x76.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-76x76.png')
    get 'apple-touch-icon-120x120-precomposed.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-120x120-precomposed.png')
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
    validates :date, presence: true
    has_many :client_schedules, dependent: :destroy
    accepts_nested_attributes_for :client_schedules, :reject_if => lambda { |a| a[:client_street_address].blank? }, :allow_destroy => true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.order(date: :asc)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    @schedule.client_schedules.build
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:date, client_schedules_attributes: [:id, :client_id, :client_street_address, :time, :service_type, :notes, :done, :price, :_destroy])
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_client_schedule.html.erb
<tr>
  <td>
    <%= f.hidden_field :_destroy, as: :hidden %>
    <%= link_to 'Delete', '#', class: 'remove_record' %>
  </td>
  <td>
    <%= f.text_field :client_street_address, data: {autocomplete_source: Client.order(:name).map { |c| { :label => c.name+' | '+c.street_address, :value => c.name+' | '+c.street_address, :id => c.id} } }, class: 'client_schedule_input', style: 'width: 90%;', :autocomplete => :off  %>
  </td>
  <td>
    <%= f.select(:time, Service::TIME, {include_blank: true }, style: 'width: 90%;', onmousedown: "if(this.options.length>7){this.size=7;}",  onchange:'this.size=0;', onblur:"this.size=0;") %></td>
  </td>
  <td>
    <%= f.select(:service_type, ServiceType.all.pluck(:description), {include_blank: true }, style: 'width: 90%;', class: 'client_schedule_service_type') %></td>
  </td>
  <td>
    <%= f.text_field :notes, style: 'width: 90%;' %></td>
  </td>
  <td>
    <%= f.check_box :done, style: 'width: 90%;', disabled: f.object.done %></td>
    <%#= f.object.id %>
  </td>
  <td>
    <%= f.text_field :price, style: 'width: 90%;' %></td>
    <%#= f.object.id %>
  </td>
</tr>

app/views/schedules/_form.html.erb
<!-- /public is root folder of Rails project -->
<link rel="stylesheet" href="/jquery-ui.css">
<!--<script src="/jquery.timepicker.min.js"></script>
<link rel="stylesheet" href="/jquery.timepicker.min.css">-->

<%= form_for(@schedule) do |f| %>
<% if @schedule.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this client from being saved:</h2>

    <ul>
    <% @schedule.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :autocomplete => :off, :style => "width: 220px;font-size:13px;" %>
  </div>

<div id="schedules" class="card">
  <div class="table-responsive card-body">
     <table id="schedules_table" class='card-body table table-striped table-bordered table-hover table-condensed table-responsive'>
       <thead>
         <tr>
           <th>Delete?</th>
           <th style="width: 285px;">Client</th>
           <th>Time</th>
           <th>Service Type</th>
           <th>Observation</th>
           <th>Done?</th>
           <th>Price</th>
         </tr>
       </thead>
       <tbody class='fields'>
         <%= f.fields_for :client_schedules do |builder| %>
           <%= render 'client_schedule', f: builder %>
         <% end %>
       </tbody>
     </table>

    <div class="actions" style="margin-left: 7px;">
      <%= f.submit class: "btn btn-outline-success my-2 my-sm-0" %>
      <%= link_to_add_row('Add Client', f, :client_schedules, class: 'btn btn-outline-success my-2 my-sm-0') %>
    </div>
    <% end %>
  </div>
  <%= render 'map2' %>
</div>
<script>

$(function() {
  $("#schedule_date").datepicker({ dateFormat: 'dd/mm/yy' });
});

 $( function() {
    $(".client_schedule_input").autocomplete({
      source: $(".client_schedule_input").data('autocomplete-source')
    });
  } );

// Runs function every second
var myVar = setInterval(test, 1000);
function test() {
    $(".client_schedule_input").autocomplete({
      source: $(".client_schedule_input").data('autocomplete-source')
    });
}

$('.client_schedule_service_type').change(function() {
  // Need service text and client_id
  service = this.value;
  console.log(service);
  temp = $(this)
  name_address = $(this).closest("td").prev().prev().find('input').val();
  console.log(name_address);
  id = 0;
  url = "/last_service_prices_by_name_address?name_address="+name_address+"&description="+service;
  encoded_url = "/last_service_prices_by_name_address?name_address="+encodeURIComponent(name_address)+"&description="+encodeURIComponent(service)
  $.getJSON(encoded_url, function(data){
    console.log(data)
    if (data && data.length > 0) {
      price = data[0]
      temp.closest("td").next().next().next().find('input').val(price);
      if (data.length > 1) {
        alert("Past prices used: \n"+ data.join("\n"));
      }
    } else {
      temp.closest("td").next().next().next().find('input').val('');
    }
  });
});

</script>

<style>
#ui-datepicker-div{
 width: 220px;
}
</style>

app/views/schedules/_map.html.erb
<%
    # Center of map - Center of DMV area according to Google
    lat = '38.889931'
    lng = ' -77.009003'
    clients = Client.all
%>

<div id="map_wrapper">
  <div id="map"></div>
</div>

<script>
  function initialize() {
    var center = new google.maps.LatLng(<%=lat%>, <%=lng%>);

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 7,
      center: center,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var data = [
      <% clients.each_with_index do |client, index| %>
        <%
            latitude = client.lat
            longitude = client.lng
        %>
        <% if index == clients.size - 1 %>
         ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>],
         ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>]
         /* Add last one twice due to API bug */
        <% else %>
         ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>],
        <% end %>
       <% end %>
    ];

    console.log(data)
    var infowindow = new google.maps.InfoWindow();

    var markers = [];
    for (var i = 0; i < data.length-1; i++) {
      var latLng = new google.maps.LatLng(data[i][1],
          data[i][2]);
      var marker = new google.maps.Marker({
        position: latLng
      });
      markers.push(marker);

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(data[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
    var markerCluster = new MarkerClusterer(map, markers, {imagePath: 'https://googlemaps.github.io/js-marker-clusterer/images/m'});

    /*
    https://googlemaps.github.io/js-marker-clusterer/images/m1.png
    https://googlemaps.github.io/js-marker-clusterer/images/m2.png
    https://googlemaps.github.io/js-marker-clusterer/images/m3.png
    https://googlemaps.github.io/js-marker-clusterer/images/m4.png
    https://googlemaps.github.io/js-marker-clusterer/images/m5.png
    ...
    */
  }
  google.maps.event.addDomListener(window, 'load', initialize);

</script>

<style>
  #map_wrapper {
    height: 600px;
    margin: 20px 0px 0px 0px;
  }

  #map {
    width: 100%;
    height: 100%;
  }
</style>

app/views/schedules/_map2.html.erb
<%
    # Center of map - Center of DMV area according to Google
    lat = '38.889931'
    lng = ' -77.009003'
    clients = Client.all
%>

<div id="map_wrapper">
  <div id="map"></div>
</div>

   <script type="text/javascript">
    $(function loadScript(){
     var data = [
       <% clients.each_with_index do |client, index| %>
         <%
             latitude = client.lat
             longitude = client.lng
         %>
         <% if index == clients.size - 1 %>
          ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>],
          ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>]
          /* Add last one twice due to API bug */
         <% else %>
          ['<%= client.name + ' | ' + client.street_address%>',<%=latitude if latitude%>,<%=longitude if longitude%>],
         <% end %>
        <% end %>
     ];
     console.log(data)


     var map = new google.maps.Map(document.getElementById('map'), {
       zoom: 8,
       center: new google.maps.LatLng(<%=lat%>, <%=lng%>),
       mapTypeId: google.maps.MapTypeId.ROADMAP
     });

     var infowindow = new google.maps.InfoWindow();

     var markers = [];
     for (var i = 0; i < data.length-1; i++) {
       var latLng = new google.maps.LatLng(data[i][1],
           data[i][2]);
       var marker = new google.maps.Marker({
         position: latLng
       });
       markers.push(marker);

       google.maps.event.addListener(marker, 'click', (function(marker, i) {
         return function() {
           infowindow.setContent(data[i][0]);
           infowindow.open(map, marker);
         }
       })(marker, i));
     }
     var markerCluster = new MarkerClusterer(map, markers, {imagePath: 'https://googlemaps.github.io/js-marker-clusterer/images/m'});
   })

   </script>

   <style>
     #map_wrapper {
       height: 600px;
       margin: 20px 0px 0px 0px;
     }

     #map {
       width: 100%;
       height: 100%;
     }
   </style>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to 'Show', @schedule %> |
  <%= link_to 'Back', schedules_path %>
  </br></br></br>
</span>

app/views/schedules/index.html.erb
<h3 style="font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('schedules') %></h3>

<div id="schedules" class="card">
  <div class="table-responsive card-body">
    <table id="schedules_table" class="card-body table table-striped table-bordered table-hover table-condensed table-responsive">
      <thead>
        <tr>
          <th style="width: 35%;"><%= t('date') %></th>
          <th style="width: 50%;"><%= t('clients') %></th>
          <th style="width: 25%;"colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.date.strftime("%A, %m/%d/%Y") %></td>
            <td><%= schedule.client_schedules.map(&:client).map(&:name).join(', ') if schedule.client_schedules.map(&:client) %></td>
            <td><%= link_to t('details'), schedule %></td>
            <td><%= link_to t('edit'), edit_schedule_path(schedule) %></td>
            <td><%= link_to t('delete'), schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<span class="page_footer">
  <%= link_to t('new_schedule'), new_schedule_path %>
</span>

<br><br>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to 'Back', schedules_path %>
  <br/><br/><br/>
</span>

app/views/schedules/show.html.erb
<p>
  <h3>Schedule for <strong><%= @schedule.date.strftime("%A, %m/%d/%Y") %></strong></h3>
</p>

<div id="schedules" class="card">
  <div class="table-responsive card-body">
   <table id="schedules_table" class='card-body table table-striped table-bordered table-hover table-condensed table-responsive'>
    <thead>
      <tr>
        <th style="width: 15%;"><%= t('name') %></th>
        <th style="width: 30%;"><%= t('address') %></th>
        <th style="width: 05%;"><%= t('time') %></th>
        <th style="width: 20%;"><%= t('service_type') %></th>
        <th style="width: 15%;"><%= t('observation') %></th>
        <th style="width: 05%;"><%= t('done') %>?</th>
        <th style="width: 20%;"><%= t('directions') %></th>
      </tr>
    </thead>
    <tbody class='fields'>
      <% @schedule.client_schedules.each do |cs| %>
       <tr>
         <%
             lat = cs.client.lat
             lng = cs.client.lng
         %>
         <td><b><%= link_to cs.client.name, cs.client %></b></td>
         <td><%= cs.client.street_address %>
         <%= cs.client.city %> </td>
         <td><%= cs.time %></td>
         <td><%= cs.service_type %></td>
         <td><%= cs.notes %> </td>
         <td><%= cs.done ? t('yes') : t('no') %></td>
         <td><%= link_to 'Click Here', "http://maps.apple.com/?q=#{lat},#{lng}", style: 'color: #68b468;'%></br></td>
       </tr>
      <% end %>
    </tbody>
   </table>
  </div>
</div>

<span class="page_footer">
  <%= link_to t('edit'), edit_schedule_path(@schedule) %> |
  <%= link_to t('back'), schedules_path %>
  </br></br></br>
</span>