config/routes.rb
Rails.application.routes.draw do
  resources :service_types
  resources :schedules
  resources :expenses
  resources :estimates
  resources :charges
  resources :shipping_addresses
    devise_for :admins
    root 'home#home'
    resources :invoices
    get 'invoices_show_all' => 'invoices#show_all', as: 'show_all'
    get 'create_monthly_invoices' => 'clients#create_monthly_invoices'
    get 'last_service_price' => 'clients#last_service_price'
    get 'last_service_prices_by_name_address' => 'clients#last_service_prices_by_name_address'
    resources :clients
    resources :services
    post 'invoices/payment_reminder'
    get 'invoice_letter/:id' => 'invoices#letter', as: 'invoice_letter'
    post 'create_services' => 'clients#create_services'
    get 'home' => 'home#home'
    get 'prospects' => 'clients#prospects'
    get 'dashboard' => 'expenses#index'
    get 'schedule', :to => redirect('schedule.erb.html')
    get 'googlea87d8b3af5e98ec8.html', :to => redirect('googlea87d8b3af5e98ec8.html')
    get 'favicon.ico', :to => redirect('https://pandera.ml/images/pandera_app/favicon-32x32.png')
    get 'apple-touch-icon.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon.png')
    get 'apple-touch-icon-76x76.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-76x76.png')
    get 'apple-touch-icon-120x120-precomposed.png', :to => redirect('https://pandera.ml/images/pandera_app/apple-touch-icon-120x120-precomposed.png')
end

app/models/client.rb
class Client < ActiveRecord::Base
    has_many :services, foreign_key: "client_id", dependent: :destroy
    has_many :invoices, foreign_key: "client_id", dependent: :destroy
    has_many :estimates, foreign_key: "client_id", dependent: :destroy
    validates :name, presence: true#, uniqueness: true
    validates :street_address, presence: true
    #validates :email, presence: true
    #validates :phone, presence: true

    CARRIERS = [['' ,''],
                ['AT&T' ,'@txt.att.net'],
                ['Boost Mobile' ,'@sms.myboostmobile.com'],
                ['Sprint' ,'@messaging.sprintpcs.com'],
                ['T-Mobile' ,'@tmomail.net'],
                ['U.S. Celular' ,'@email.uscc.net'],
                ['Verizon' ,'@vtext.com'],
                ['Virgin Mobile' ,'@vmobl.com'],
                ['Altel' ,'@sms.altelwireless.com']]

    def self.search(search)
        if search
            where('name ILIKE ? OR email ILIKE ? OR phone ILIKE ? OR CAST( dob AS text ) ILIKE ?
				OR city ILIKE ? OR zipcode ILIKE ? OR street_address ILIKE ?',
             "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%",
             "%#{search}%", "%#{search}%")
        else
            where(nil)
        end
    end

    def curated_phone
        self.phone.gsub(Regexp.union('(', ')', '-',' ', '+1','.'), '')
    end
    def curated_phone2
        self.phone2.gsub(Regexp.union('(', ')', '-',' ', '+1','.'), '')
    end

    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |client|
          csv << client.attributes.values_at(*column_names)
        end
      end
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.includes(:services).where('prospect = ? OR prospect IS ?', false, nil).search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
    #@clients = Client.search(params[:search]).order("created_at DESC").paginate(:per_page => 15, :page => params[:page])
    respond_to do |format|
      format.html
      format.csv { send_data Client.all.to_csv }
			#format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /prospects
  # GET /prospects.json
  def prospects
    @prospects = Client.includes(:services).where(prospect: true).search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
    respond_to do |format|
      format.html
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    location = Geocoder.search(@client.street_address)
    if location && location[0]
      @client.lat = location[0].latitude
      @client.lng = location[0].longitude
    end

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_services
    services = params[:service]

    dates = [ services[:date1], services[:date2], services[:date3], services[:date4], services[:date5], services[:date6] ]
    services[:quantity].to_i.times do |i|
      s = Service.create(date: dates[i].to_date ,client_id: client_params[:id], description: services[:description], notes: services[:notes], price: services[:price])
    end
    respond_to do |format|
        format.js { redirect_to clients_path, notice: 'Services were successfully added.' }
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    location = Geocoder.search(@client.street_address)
    if location && location[0]
      @client.lat = location[0].latitude
      @client.lng = location[0].longitude
    end

    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def create_monthly_invoices
    @invoice_num = 0
    # Clients that need invoices
    @clients = Client.joins(:services).where("invoice_id IS NULL").uniq
    @clients.each do |client|
      invoice = Invoice.new(client_id: client.id, maturity: Date.today + 30, description: Date.today.strftime("%B").to_s + ' invoice')
      invoice.services = client.services.where("invoice_id IS NULL")
      invoice.save!
      InvoiceMailer.invoice_created(invoice).deliver_now if client.email.present?
      InvoiceSmsMailer.invoice_created(invoice).deliver_now if client.phone.present? && client.sms_gateway.present?
      invoice.services.each do |srvc|
        srvc.invoice_id = invoice.id
        srvc.save!
      end
      @invoice_num += 1
    end
  end

  def last_service_price
    @client = Client.find(params[:id])
    description = params[:description]
    last_price = @client.services.where(description: description).last.price if @client.services.where(description: description).last
    respond_to do |format|
      format.json { render :json => last_price }
    end
  end

  def last_service_prices_by_name_address
    client_name = params[:name_address][0..params[:name_address].index(' | ')-1]
    client_address = params[:name_address][params[:name_address].index(' | ')+3..params[:name_address].length-1]
    @client = Client.find_by_name_and_street_address(client_name, client_address)
    description = params[:description]
    last_prices = @client.services.where(description: description).order('created_at DESC').map(&:price).uniq if @client.services.where(description: description).last
    respond_to do |format|
      format.json { render :json => last_prices }
      # For testing convenience: in console => app.get("/last_service_prices_by_name_address?name_address=Rick%20%7C%204017%20peppertree%20ln&description=Bi-weekly%20Cutting")
      format.html { render :html => last_prices }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:id, :name, :street_address, :city, :state, :zipcode, :email, :email2, :phone, :phone2, :dob, :sms_gateway, :sms_gateway2, :notes, :credit, :prospect, :lat, :lng)
    end

    def sort_column
      Client.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('name') %><br>
    <%= f.text_field :name, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('address') %><br>
    <%= f.text_field :street_address, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('city') %><br>
    <%= f.text_field :city, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('state') %><br>
    <%= f.text_field :state, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('zipcode') %><br>
    <%= f.text_field :zipcode, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('email') %><br>
    <%= f.text_field :email, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('email2') %><br>
    <%= f.text_field :email2, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('phone') %><br>
    <%= f.text_field :phone, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
  <%= f.label t('carrier') %><br>
  <%= f.select :sms_gateway, options_for_select(Client::CARRIERS, @client.sms_gateway), {}, {class: 'sms_gateway custom-select', style: "width: 30%"} %>
  </div>
  <div class="field">
    <%= f.label t('phone2') %><br>
    <%= f.text_field :phone2, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('carrier2') %><br>
    <%= f.select :sms_gateway2, options_for_select(Client::CARRIERS, @client.sms_gateway2), {}, {class: 'sms_gateway2 custom-select', style: "width: 30%"} %>
  </div>
  <div class="field">
    <%= f.label t('notes') %><br>
    <%= f.text_area :notes, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%= f.label t('credit') %><br>
    <%= f.text_field :credit, class: "form-control", style: "width: 25%" %>
  </div>
  <div class="field">
    <%#= f.label 'test' TODO fix month dropdown render AND send emails with rigth link page one %>
    <%= f.label t('dob') %><br>
    <%= f.date_select :dob, {:order => [:month, :day, :year], :start_year => Time.now.year - 80, use_month_numbers: true}, {:class => "custom-select", style: "width: 10%"} %>
  </div>
  <div class="field">
    <%= f.label t('prospect')+'?' %><br>
    <%= f.check_box(:prospect) %>
  </div>
  <div class="actions">
    <%= f.submit t('save'), class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/clients/create_monthly_invoices.html.erb
<%= @invoice_num.to_s + ' invoices were created' %> <br/><br/>

<%= link_to 'Back', clients_path %>

app/views/clients/edit.html.erb
<h1><%= t('editing_client') %></h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to t('details'), @client %> |
  <%= link_to t('back'), clients_path %>
</span> </br></br></br>

app/views/clients/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://jqueryui.com/resources/demos/style.css">

<!--<h1 style="font-size: 36px;font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('clients') %></h1> -->
<h3 style="font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('clients') %></h3>
<%= form_tag clients_path, :method => 'get', :id => "clients_search", :style => "margin: -36px 0 0 0;" do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <b><%= t('search') %>:  </b><%= text_field_tag :search, params[:search], style: "display: initial" %>
  </p>
<% end %>

<div id="clients" class="card">
	<div class="table-responsive card-body">
		<table id="clients_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
		  <thead>
			<tr>
        <th style="width: 15%;"><%= t('name') %></th>
        <th style="width: 25%;"><%= t('address') %></th>
        <th style="width: 15%;"><%= t('email') %></th>
        <th style="width: 15%;"><%= t('phone') %></th>
        <!--<th style="width: 10%;"><%#= t('dob') %></th>-->
        <th style="padding-right:20px;width: 15%;"><%= t('carrier') %></th>
			  <th colspan="7"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @clients.each do |client| %>
			  <% crt_inv = client.services.where("paid IS NOT TRUE").where("invoice_id IS NULL").length >= 1  %>
			  <tr <%= 'class=client_tr' if crt_inv %>>
				<td><%= client.name %></td>
				<td><%= client.street_address %></td>
				<td><%= client.email %></td>
				<td><%= client.phone %></td>
				<!--<td><%#= client.dob %></td>-->
				<td><%= Client::CARRIERS.select{ |carrier, email| email == client.sms_gateway }[0][0] if client.sms_gateway %></td>
				<td><%= link_to t('make_estimate'), new_estimate_path(:client_id => client.id) %></td>
							<td><a class="create-services" id="<%= client.id %>" name="<%= client.name %>"><%= t('charge_services') %></a></td>
				<td <%= 'class=client_td' if crt_inv %>><%= link_to_if(crt_inv,t('create_invoice'), new_invoice_path(:client_id => client.id) ) %></td>
				<td><%= link_to t('details'), client %></td>
				<td><%= link_to t('edit'), edit_client_path(client) %></td>
				<td><%= link_to t('delete'), client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	</div>
</div>

<span class="page_footer">
  <%= link_to t('new_client'), new_client_path %> |
  <%= link_to t('create_all_monthly_invoices'), create_monthly_invoices_path %> |
</span>
<!--<p style="text-align: right;margin-top:-19px;"> -->
<span class="page_footer">
  Download:
  <%= link_to "CSV", clients_path(format: "csv") %>
  <!--| <%#= link_to "Excel", clients_path(format: "xls") %> -->
</span>

<br/>
<%= will_paginate @clients, :previous_label => t('previous'), :next_label => t('next'), inner_window: 1, outer_window: 0 %> </br>
<br/>

  <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
		.ui-dialog-titlebar{ background-color: #68b468;}
  </style>

<script>
    $( "#clients_search" ).keyup(function() {
        search = $('#search').val();
        $.get( "/clients?search="+search, function( data ) {
            data_html_obj = $($.parseHTML( data ) );
            div = data_html_obj.find('#clients');
            $('#clients').html(div);
        });
    });
</script>

app/views/clients/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.released_on %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<span class="page_footer">
  <%= link_to 'Back', clients_path %>
</span> </br></br></br>

app/views/clients/prospects.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://jqueryui.com/resources/demos/style.css">

<h3 style="font-family: verdana, arial, helvetica, sans-serif;" class="page_title"><%= t('prospects') %></h3>
<!--<%#= form_tag prospects_path, :method => 'get', :id => "prospects_search", :style => "margin: -36px 0 0 0;" do %>
  <%#= hidden_field_tag :direction, params[:direction] %>
  <%#= hidden_field_tag :sort, params[:sort] %>
  <p>
    <b>Search:  </b><%#= text_field_tag :search, params[:search], style: "display: initial" %>
  </p>
<%# end %>-->

<div id="prospects" class="card">
	<div class="table-responsive card-body">
		<table id="prospects_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
		  <thead>
			<tr>
			  <th style="width: 15%;"><%= t('name')%></th>
			  <th style="width: 25%;"><%= t('adress')%></th>
			  <th style="width: 15%;"><%= t('email')%></th>
			  <th style="width: 15%;"><%= t('phone')%></th>
			  <th style="width: 10%;"><%= t('dob')%></th>
			  <th style="padding-right:20px;width: 15%;"><%= t('carrier')%></th>
			  <th colspan="7"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @prospects.each do |prospect| %>
			  <% crt_inv = prospect.services.where("paid IS NOT TRUE").where("invoice_id IS NULL").length >= 1  %>
			  <tr <%= 'class=client_tr' if crt_inv %>>
				<td><%= prospect.name %></td>
				<td><%= prospect.street_address %></td>
				<td><%= prospect.email %></td>
				<td><%= prospect.phone %></td>
				<td><%= prospect.dob %></td>
				<td><%= Client::CARRIERS.select{ |carrier, email| email == prospect.sms_gateway }[0][0] if prospect.sms_gateway %></td>
				<td><%= link_to 'Make Estimate', new_estimate_path(:client_id => prospect.id) %></td>
							<td><a class="create-services" id="<%= prospect.id %>" name="<%= prospect.name %>"><%= t('charge_services') %></a></td>
				<td <%= 'class=client_td' if crt_inv %>><%= link_to_if(crt_inv,'Create Invoice', new_invoice_path(:client_id => prospect.id) ) %></td>
				<td><%= link_to t('details'), prospect %></td>
				<td><%= link_to t('edit'), edit_client_path(prospect) %></td>
				<td><%= link_to t('delete'), prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	</div>
</div>

<span  class="page_footer">
	<%= link_to t('new_client'), new_client_path %>
</span>

<br/>
<%= will_paginate @prospects %> </br>
<br/>

  <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
		.ui-dialog-titlebar{ background-color: #68b468;}
  </style>

<script>
    $( "#clients_search" ).keyup(function() {
        search = $('#search').val();
        $.get( "/clients?search="+search, function( data ) {
            data_html_obj = $($.parseHTML( data ) );
            div = data_html_obj.find('#clients');
            $('#clients').html(div);
        });
    });
</script>

app/views/clients/show.html.erb
<p style="width: 200px;">
  <strong><%= t('name') %>:</strong>
  <%= @client.name %>
</p>

<p style="width: 200px;">
  <strong><%= t('address') %>:</strong>
  <%= @client.street_address %>
</p>

<p>
  <strong><%= t('city') %>:</strong>
  <%= @client.city %>
</p>

<p>
  <strong><%= t('state') %>:</strong>
  <%= @client.state %>
</p>

<p>
  <strong><%= t('zipcode') %>:</strong>
  <%= @client.zipcode %>
</p>

<p style="width: 200px;">
  <strong><%= t('email') %>:</strong>
  <%= @client.email %>
</p>

<p style="width: 200px;">
  <strong><%= t('email2') %>:</strong>
  <%= @client.email2 %>
</p>


<p>
  <strong><%= t('phone') %>:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong><%= t('carrier') %>:</strong>
  <%= Client::CARRIERS.select{ |carrier, email| email == @client.sms_gateway }[0][0] if @client.sms_gateway %>
</p>

<p>
  <strong><%= t('phone2') %>:</strong>
  <%= @client.phone2 %>
</p>

<p>
  <strong><%= t('carrier2') %>:</strong>
  <%= Client::CARRIERS.select{ |carrier, email| email == @client.sms_gateway }[0][0] if @client.sms_gateway2 %>
</p>

<p>
  <strong><%= t('dob') %>:</strong>
  <%= @client.dob %>
</p>

<p style="width: 200px;">
  <strong><%= t('notes') %>:</strong>
  <%= @client.notes %>
</p>

<p>
  <strong><%= t('credit') %>:</strong>
  <%= @client.credit %>
</p>

<p>
  <strong><%= t('prospect') %>:</strong>
  <%= @client.prospect %>
</p>

<p>
  <strong><%= t('latitude') %>:</strong>
  <%= @client.lat %>
</p>

<p>
  <strong><%= t('longitude') %>:</strong>
  <%= @client.lng %>
</p>

<div id="map_wrapper">
  <div id="map"></div>
</div>

   <script type="text/javascript">
    $(function loadScript(){
     var locations = [
         ['<%= link_to 'Directions', "http://maps.apple.com/?q=#{@client.lat},#{@client.lng}"%>', <%= @client.lat %> , <%= @client.lng %>]
     ];

     var map = new google.maps.Map(document.getElementById('map'), {
   zoom: 20,
   center: new google.maps.LatLng(<%= @client.lat %>,<%= @client.lng %>),
   mapTypeId: google.maps.MapTypeId.SATELLITE
 });

     var infowindow = new google.maps.InfoWindow();

     var marker, i;

     for (i = 0; i < locations.length; i++) {
        marker = new google.maps.Marker({
           position: new google.maps.LatLng(locations[i][1], locations[i][2]),
           map: map,
           icon: greenPin
         });

       google.maps.event.addListener(marker, 'click', (function(marker, i) {
         return function() {
           infowindow.setContent(locations[i][0]);
           infowindow.open(map, marker);
         }
       })(marker, i));
     }
   })

   </script>

   <style>
   #map_wrapper {
     height: 355px;
     margin: -360px 0px 0 210px;
   }

   #map {
       width: 100%;
       height: 100%;
   }
   @media (max-width: 550px) {
       #map_wrapper {
         margin: 0px 0px 0px 0px;
       }
   }
   </style>
   <br/>
   <h1><%= t('services') %> </h1>
   <div id="services" class="card">
       <div class="table-responsive card-body">
           <table id="services_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
             <thead>
               <tr>
                 <th style="width: 35%;"><%= t('client') %></th>
                 <th style="width: 15%;"><%= t('date') %></th>
                 <th style="width: 15%;"><%= t('description') %></th>
                 <th style="width: 5%;"><%= t('price') %></th>
                 <th style="width: 15%;"><%= t('maturity') %></th>
                 <th style="width: 10%;"><%= t('invoice') %></th>
                 <th style="width: 5%;"><%= t('paid') %></th>
                 <th colspan="3"></th>
               </tr>
             </thead>

             <tbody>
               <% @client.services.each do |service| %>
                 <tr>
                   <td><%= link_to service.client.name, service.client %></td>
                   <td><%= service.date %></td>
                   <td><%= service.description %></td>
                   <td><%= service.price %></td>
                   <td><%= service.maturity %></td>
                   <td><%= link_to service.invoice.id, invoice_path(service.invoice.id, :format => :pdf) if service.invoice %></td>
                   <td><%= service.paid? ? t('yes') : t('no') %></td>
                   <td><%= link_to t('details'), service %></td>
                   <td><%= link_to t('edit'), edit_service_path(service) %></td>
                   <td><%= link_to t('delete'), service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                 </tr>
               <% end %>
             </tbody>
           </table>
       </div>
   </div>

   <span class="page_footer">
     <%= link_to t('edit'), edit_client_path(@client) %> |
     <%= link_to t('back'), clients_path %>
   </span> </br></br></br>

app/views/clients/showOLD.html.erb
<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @client.zipcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @client.dob %>
</p>

<h3>User Invoices</h3>

<div class="table-responsive">
  <table id="new_checklist_table" class="table table-striped table-bordered table-hover table-condensed table-responsive">
    <thead>
      <tr>
        <th>Invoice number</th>
        <th>Maturity</th>
        <th>Date of service</th>
        <th>Description</th>
        <th>Price</th>
        <th>Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @client.invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.invoice_number %></td>
          <td><%= invoice.maturity %></td>
          <td><%= invoice.date_of_service %></td>
          <td><%= invoice.description %></td>
          <td><%= invoice.price %></td>
              <% prices = invoice.client.invoices.where("paid IS FALSE").pluck(:price) %>
          <td><%= '$' if prices.length>=1 %><%= prices.inject(0){|sum,x| sum + x } %></td>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>



<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>